/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.projectlombok.lombok)
    api(libs.org.springframework.boot.spring.boot.starter.thymeleaf)
    api(libs.mysql.mysql.connector.java)
    api(libs.org.springframework.boot.spring.boot.starter.data.jdbc)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.spring.core)
    api(libs.jstl.jstl)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.com.googlecode.json.simple.json.simple)
    api(libs.org.springframework.boot.spring.boot.starter.mail)
    api(libs.org.apache.poi.poi.ooxml)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    runtimeOnly(libs.com.h2database.h2)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
}

group = "duan"
version = "0.0.1-SNAPSHOT"
description = "Sportify"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
